# Generated by Django 4.2 on 2023-05-04 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_acces_sim_compte_facturation_etat_forfait_operateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suivi_consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20, verbose_name='Mois')),
                ('montantVoix', models.FloatField(verbose_name='Montant Voix')),
                ('montantData', models.FloatField(verbose_name='Montant Data')),
                ('forfait', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.forfait')),
                ('sim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.sim')),
            ],
        ),
    ]
