# Generated by Django 4.2 on 2023-05-04 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_suivi_consommation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=40, verbose_name='Classe')),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.etat')),
            ],
        ),
        migrations.CreateModel(
            name='Habilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellePage', models.CharField(max_length=60, verbose_name='Libelle Page')),
                ('vRead', models.BooleanField(verbose_name='Affichage')),
                ('vWrite', models.BooleanField(verbose_name='Création')),
                ('vUpdate', models.BooleanField(verbose_name='Modification')),
                ('vDelete', models.BooleanField(verbose_name='Suppression')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.profil')),
            ],
        ),
    ]
