# Generated by Django 4.2 on 2023-05-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0006_alter_etat_libelle_alter_profil_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etat',
            name='libelle',
            field=models.CharField(default='Actif', max_length=30, verbose_name='Etat'),
        ),
    ]
