# Generated by Django 4.2 on 2023-05-11 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0007_alter_etat_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acces_sim',
            name='libelle',
            field=models.CharField(max_length=20, verbose_name='Accès'),
        ),
        migrations.AlterField(
            model_name='affectation_sim',
            name='collaborateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.collaborateur', verbose_name='Collaborateur'),
        ),
        migrations.AlterField(
            model_name='affectation_sim',
            name='dateAffectation',
            field=models.DateField(auto_now=True, verbose_name="Date d'affectation"),
        ),
        migrations.AlterField(
            model_name='affectation_sim',
            name='dateDesactivation',
            field=models.DateField(auto_now=True, verbose_name='Date de désactivation'),
        ),
        migrations.AlterField(
            model_name='affectation_sim',
            name='dateModification',
            field=models.DateField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='affectation_sim',
            name='sim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.sim', verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='affectation_sim',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.ticket', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.classe', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.departement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='matricule',
            field=models.CharField(max_length=7, unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='forfait',
            name='montant',
            field=models.IntegerField(verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='forfait',
            name='montantPlafondData',
            field=models.IntegerField(verbose_name='Montant Plafond Data'),
        ),
        migrations.AlterField(
            model_name='forfait',
            name='montantPlafondVoix',
            field=models.IntegerField(verbose_name='Montant Plafond Voix'),
        ),
        migrations.AlterField(
            model_name='forfait',
            name='plafondInterne',
            field=models.IntegerField(verbose_name='Plafond Interne'),
        ),
        migrations.AlterField(
            model_name='forfait',
            name='typeSim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.type_sim', verbose_name='Type de SIM'),
        ),
        migrations.AlterField(
            model_name='habilitation',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.profil', verbose_name='Profil'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='etat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.etat', verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='acces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.acces_sim', verbose_name='Accès'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='etat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.etat', verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='forfait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.forfait', verbose_name='Forfait'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='operateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.operateur', verbose_name='Opérateur'),
        ),
        migrations.AlterField(
            model_name='suivi_consommation',
            name='forfait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.forfait', verbose_name='Forfait'),
        ),
        migrations.AlterField(
            model_name='suivi_consommation',
            name='sim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.sim', verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='compte_facturation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.compte_facturation', verbose_name='Compte de Facturation'),
        ),
        migrations.AlterField(
            model_name='type_sim',
            name='libelle',
            field=models.CharField(max_length=20, unique=True, verbose_name='Type de SIM'),
        ),
    ]
