# Generated by Django 4.2 on 2023-05-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0012_alter_operateur_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateur',
            name='identifiant',
            field=models.IntegerField(max_length=4, verbose_name='Identifiant'),
        ),
    ]
