# Generated by Django 4.2 on 2023-05-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0013_alter_operateur_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateur',
            name='identifiant',
            field=models.IntegerField(verbose_name='Identifiant'),
        ),
    ]
