# Generated by Django 4.2 on 2023-05-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0014_alter_operateur_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forfait',
            name='montantPlafondData',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant Plafond Data'),
        ),
        migrations.AlterField(
            model_name='forfait',
            name='montantPlafondVoix',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant Plafond Voix'),
        ),
    ]
