# Generated by Django 4.2 on 2023-05-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0015_alter_forfait_montantplafonddata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='adresseIP',
            field=models.CharField(verbose_name='Adresse IP'),
        ),
    ]
