# Generated by Django 4.2 on 2023-05-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0016_alter_sim_adresseip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation_sim',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.ticket', verbose_name='Numéro Ticket'),
        ),
    ]
