# Generated by Django 4.2 on 2023-05-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0018_alter_collaborateur_matricule_alter_sim_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation_sim',
            name='dateDesactivation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de désactivation'),
        ),
        migrations.AlterField(
            model_name='affectation_sim',
            name='dateModification',
            field=models.DateField(blank=True, null=True, verbose_name='Date de modification'),
        ),
    ]
