# Generated by Django 4.2 on 2023-05-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0019_alter_affectation_sim_datedesactivation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='numero',
            new_name='numero_ticket',
        ),
    ]
