# Generated by Django 4.1.6 on 2023-05-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0020_rename_numero_ticket_numero_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='matricule',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='adresseIP',
            field=models.CharField(max_length=30, verbose_name='Adresse IP'),
        ),
    ]
