# Generated by Django 4.2 on 2023-05-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0020_rename_numero_ticket_numero_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='adresseIP',
            field=models.CharField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
    ]
