# Generated by Django 4.1.6 on 2023-06-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0021_alter_collaborateur_matricule_alter_sim_adresseip'),
        ('sim', '0021_alter_sim_adresseip'),
    ]

    operations = [
    ]
