# Generated by Django 4.1.6 on 2023-06-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0022_merge_20230605_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='adresseIP',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Adresse IP'),
        ),
    ]
