# Generated by Django 4.2 on 2023-06-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0023_alter_sim_adresseip'),
    ]

    operations = [
        migrations.AddField(
            model_name='forfait',
            name='effectif',
            field=models.DateField(null=True),
        ),
    ]
