# Generated by Django 4.2 on 2023-06-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0024_forfait_effectif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forfait',
            name='effectif',
        ),
    ]
