# Generated by Django 4.2 on 2023-05-04 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sim', '0003_suivi_consommation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAffectation', models.DateField(auto_now=True, verbose_name="Dade d'affectaion")),
                ('dateDesactivation', models.DateField(verbose_name="Dade d'affectaion")),
            ],
        ),
        migrations.CreateModel(
            name='Article_modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_modele', models.CharField(max_length=60, verbose_name='Article Modèle')),
            ],
        ),
        migrations.CreateModel(
            name='Bc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_bc', models.CharField(max_length=50, verbose_name='Bon de commande')),
                ('date_bc', models.DateField(verbose_name='Date Bon de commande')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='TELECOM', max_length=60, verbose_name='Catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Code_analytique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Code Analytique')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Emplacement')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_facture', models.CharField(max_length=60, verbose_name='Numéro facture')),
                ('dateFacture', models.DateField(verbose_name='Date facture')),
            ],
        ),
        migrations.CreateModel(
            name='Reception_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('pu_ht', models.IntegerField(verbose_name='Prix Hors Taxe')),
                ('prix_global', models.IntegerField(verbose_name='Prix global')),
                ('article_modele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.article_modele')),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteSortie', models.IntegerField(verbose_name='Quantité Sortie')),
                ('numBonSortie', models.IntegerField(verbose_name='Numéro Bon de sortie')),
                ('numSortie', models.IntegerField(verbose_name='Numéro de sortie')),
                ('reception_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.reception_article')),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Matériel')),
                ('code_analytique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.code_analytique')),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.emplacement')),
            ],
        ),
        migrations.CreateModel(
            name='Article_sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affectation_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.affectation_article')),
                ('sim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.sim')),
            ],
        ),
        migrations.AddField(
            model_name='article_modele',
            name='materiel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.materiel'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei1', models.IntegerField(verbose_name='IMEI 1')),
                ('imei2', models.IntegerField(null=True, verbose_name='IMEI 2')),
                ('imei3', models.IntegerField(null=True, verbose_name='IMEI 3')),
                ('imei4', models.IntegerField(null=True, verbose_name='IMEI 4')),
                ('article_modele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.article_modele')),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.etat')),
            ],
        ),
        migrations.AddField(
            model_name='affectation_article',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.article'),
        ),
        migrations.AddField(
            model_name='affectation_article',
            name='collaborateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.collaborateur'),
        ),
        migrations.AddField(
            model_name='affectation_article',
            name='sortie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.sortie'),
        ),
        migrations.AddField(
            model_name='affectation_article',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.ticket'),
        ),
    ]
