# Generated by Django 4.2 on 2023-05-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0002_alter_categorie_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_modele',
            name='reference_modele',
            field=models.CharField(max_length=60, verbose_name='Modèle équipement'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='libelle',
            field=models.CharField(max_length=50, verbose_name="Type d'équipement"),
        ),
    ]
