# Generated by Django 4.2 on 2023-05-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0003_alter_article_modele_reference_modele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception_article',
            name='bc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.bc'),
        ),
    ]
