# Generated by Django 4.2 on 2023-05-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipement", "0004_reception_article_bc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affectation_article",
            name="dateDesactivation",
            field=models.DateField(
                blank=True, null=True, verbose_name="Dade d'affectaion"
            ),
        ),
    ]
