# Generated by Django 4.2 on 2023-06-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0005_alter_affectation_article_datedesactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='numSortie',
            field=models.CharField(verbose_name='Numéro de sortie'),
        ),
    ]
