# Generated by Django 4.1.6 on 2023-06-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0007_alter_article_imei2_alter_article_imei3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='numSortie',
            field=models.CharField(max_length=200, verbose_name='Numéro de sortie'),
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.IntegerField(verbose_name='Disponible')),
                ('inactif', models.IntegerField(verbose_name='Inactif')),
                ('affecte', models.IntegerField(verbose_name='Affecte')),
                ('article_modele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.article_modele')),
            ],
        ),
    ]
