# Generated by Django 4.2 on 2023-06-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0009_remove_mouvement_inactif_alter_mouvement_affecte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imei1',
            field=models.CharField(verbose_name='IMEI 1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imei2',
            field=models.CharField(blank=True, null=True, verbose_name='IMEI 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imei3',
            field=models.CharField(blank=True, null=True, verbose_name='IMEI 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imei4',
            field=models.CharField(blank=True, null=True, verbose_name='IMEI 4'),
        ),
    ]
